name: Feature request
description: Suggest an improvement or new feature for YARD

body:
  - type: markdown
    attributes:
      value: |
        - Write a descriptive issue title above.
        - Search [open](https://github.com/elliotfontaine/yard-godot/issues) and [closed](https://github.com/elliotfontaine/yard-godot/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been requested.

  - type: textarea
    attributes:
      label: Problem or limitation
      description: Describe the problem you are facing or the limitation you encounter. Give context.
      placeholder: e.g. I always have to manually do X, which is tedious when...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed solution
      description: Describe what you'd like to happen. Be as specific as you can.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've tried or considered.

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
